### ISSUE TITLE
Weekly scrum –[March 12th, 2021]

### ISSUE THREAD

**Issue by thomas7carriere** [thomas7carriere/Project4806#33]
- what have I done this week?(with link(s) to the relevant GitHub Issue(s)) 
- what will I do next week?(with link(s) to the relevant GitHub Issue(s)) 
- what is holding me back? (if applicable)

**Comment by thomas7carriere** [comment]
- what have I done this week? Finished work on being able to create surveys (#10). Made tests for the SurveyController (#28)
 - what will I do next week? Implement Spring Boot Security and necessary tests (#35)
 - what is holding me back? N/A

**Comment by MikeEvans6** [comment]
- What have I done this week? Finished Survey class and unit tests #12 . Also the Jpa tests for rangeQuestion Class #19 
- What will I do next week? Implement Edit Survey feature and necessary test #37 
- what is holding me back? N/A

**Comment by kellyharrison** [comment]
- what have I done this week?:
Finished the RangeQuestion class + testing #7 and Created the schema diagram #22
- what will I do next week?:
Next week I will work on the help page feature. #38 
- what is holding me back?:
N/A

**Comment by AriSengupta** [comment]
- What have I done this week?(with link(s) to the relevant GitHub Issue(s))
Finish updating ReadMe for Milestone 1 #21
Create Tests for DTO Classes #20
Add Spring Boot Actuator Support for better debugging #24
Enable H2 Console #25

- What will I do next week?(with link(s) to the relevant GitHub Issue(s))
Add Delete Survey Feature #39 
Add Search Survey Feature #40 

- What is holding me back? (if applicable)
N/A

**Comment by cyang030** [comment]
- what have I done this week?(with link(s) to the relevant GitHub Issue(s))
  Implemented #11 view survey page
- what will I do next week?(with link(s) to the relevant GitHub Issue(s))
  #34 close survey and provide statistics
- what is holding me back? (if applicable)
   N/A

**Comment by Dom123k** [comment]
- what have I done this week?(with link(s) to the relevant GitHub Issue(s))
    Became more familiar with Java-script and Ajax to help with front end development 
- what will I do next week?(with link(s) to the relevant GitHub Issue(s))

   [#42] provide ability to save results from a survey in the repositories 

- what is holding me back? (if applicable)
   N/A
