### ISSUE TITLE
Close the survey and provide statistics

### ISSUE THREAD

**Issue by cyang030** [thomas7carriere/Project4806#34]
Add a functionally to allow user to close a survey, and at that point a survey result is generated, compiling the answers.
Depending on the amount coding required, the pie chart and histogram listed in the functional required may spun off into a new issue.

**Comment by thomas7carriere** [comment]
Maybe we should allow surveyors to see the results even if the survey is open still.

**Comment by cyang030** [comment]
> Maybe we should allow surveyors to see the results even if the survey is open still.

Current implementation calculates the statistic on the fly, so it works for both cases.

**Comment by cyang030** [comment]
Put a diff here since PR is from branch to branch

https://github.com/thomas7carriere/Project4806/compare/fe4fb811d27878c2518a125abf9cda21bcaa50c8...e72c24c4b9802acc1e7cd53926ce24dfb6c3a09a
