### ISSUE TITLE
Ability to answer surveys 

### ISSUE THREAD

**Issue by Dom123k** [thomas7carriere/Project4806#42]
Survey results should be saved in the repository

**Comment by Dom123k** [comment]
Some things need to be fixed/ looked at in the submit answers branch. It currently saves the answers with their respective question IDs in the repo

[a link to a branch](https://github.com/thomas7carriere/Project4806/tree/submitAnswers)

- Add Testing to answerDTO
- See if its possible to have a map in answerDTO instead of two arrays, and to stringify a json representation of the answerDTO 
     object in answerSurvey.js I couldnt figure out how to do this.
- A better solution to check which type of question is given back by the repository in the Post mapping of SURVEY_VIEW_ID 
     (maybe something to do with the question super class
- After adding the ID in questionDTO the assert equals for testing questionDTO  gives ambiguous error. Even though both 
     parameters are Long. To fix this temporarily it was cast to Long
- Need to check if all answers have been filled out in answerSurvey.js and give alert box if haven't been filled
- Add ability to navigate to view the list of surveys after answers have been submitted

**Comment by thomas7carriere** [comment]
- Was able to add the map to replace the 2 arrays.
 - Redirects now to survey view list page after sending answers.
 - openEnded questions no longer '+' seperated
