### ISSUE TITLE
Weekly Scrum [March 18th, 2021]

### ISSUE THREAD

**Issue by MikeEvans6** [thomas7carriere/Project4806#44]
- what have I done this week?(with link(s) to the relevant GitHub Issue(s))
- what will I do next week?(with link(s) to the relevant GitHub Issue(s))
- what is holding me back? (if applicable)

**Comment by thomas7carriere** [comment]
- what have I done this week? Added Spring security features #35 and a page that shows a users surveys #41.
 - what will I do next week? Try and help out with whatever I can
 - what is holding me back? Feeling sick

**Comment by cyang030** [comment]
- what have I done this week?(with link(s) to the relevant GitHub Issue(s))
Implementing #34 
- what will I do next week?(with link(s) to the relevant GitHub Issue(s))
Keep working on current feature implementation
- what is holding me back? (if applicable)
4th year project presentation & midterm

**Comment by Dom123k** [comment]
- what have I done this week?(with link(s) to the relevant GitHub Issue(s))
         Added feature to save answers #42 
- what will I do next week?(with link(s) to the relevant GitHub Issue(s))
         Add testing to #42 
- what is holding me back? (if applicable)
         4th year project

**Comment by AriSengupta** [comment]
- What have I done this week?(with link(s) to the relevant GitHub Issue(s))
Worked on Add Delete Survey Feature #39

- What will I do next week?(with link(s) to the relevant GitHub Issue(s))
Add Search Survey Feature #40

- What is holding me back? (if applicable)
N/A

**Comment by MikeEvans6** [comment]
- what have I done this week?(with link(s) to the relevant GitHub Issue(s)): worked on the edit survey feature #37
- what will I do next week?(with link(s) to the relevant GitHub Issue(s)): finish edit survey feature #37
- what is holding me back? (if applicable)

**Comment by kellyharrison** [comment]
- what have I done this week?
Worked on adding the help page feature #38 and UML #36

- what will I do next week?
Finish help page feature #38 and UML #36 and see if the group needs any assistance with any other open issues before milestone 2 deadline.

- what is holding me back?
N/A
