### ISSUE TITLE
Weekly Scrum [March 25th, 2021]

### ISSUE THREAD

**Issue by AriSengupta** [thomas7carriere/Project4806#53]
- what have I done this week?(with link(s) to the relevant GitHub Issue(s))
- what will I do next week?(with link(s) to the relevant GitHub Issue(s))
- what is holding me back? (if applicable)

**Comment by thomas7carriere** [comment]
- what have I done this week? Helped out with #11 ,research into using PostGres on Heroku deploy
- what will I do next week? Presentation Topic (Jib), hopefully better idea after speaking with TA
- what is holding me back? N/A

**Comment by cyang030** [comment]
- what have I done this week?
  #34 , #48 
- what will I do next week?
  Presentation Topic research, #55 
- what is holding me back?
   N/A

**Comment by AriSengupta** [comment]
- What have I done this week?(with link(s) to the relevant GitHub Issue(s))
Added Delete Survey Feature #39
Added Search Survey Feature #40

- What will I do next week?(with link(s) to the relevant GitHub Issue(s))
Add Lombok Support #56 
Presentation Topic research

- What is holding me back? (if applicable)
N/A

**Comment by Dom123k** [comment]
- what have I done this week?(with link(s) to the relevant GitHub Issue(s))
  Finished testing and implementing saving results from surveys #42 

- what will I do next week?(with link(s) to the relevant GitHub Issue(s))
  Make the website better looking #57 
  Project Presentation research

- what is holding me back? (if applicable)
   N/A

**Comment by kellyharrison** [comment]
- what have I done this week?
Presenation research and prep, completed #38 
- what will I do next week?
impliment presenation and #59 
- what is holding me back?
N/A

**Comment by MikeEvans6** [comment]
- what have I done this week?
Edit Feature and required tests #37 
- what will I do next week?
Back Button feature on all pages #61 
- what is holding me back?
N/A
