### ISSUE TITLE
Weekly Scrum [April 1st, 2021]

### ISSUE THREAD

**Issue by cyang030** [thomas7carriere/Project4806#65]
- what have I done this week?(with link(s) to the relevant GitHub Issue(s))
- what will I do next week?(with link(s) to the relevant GitHub Issue(s))
- what is holding me back? (if applicable)

**Comment by thomas7carriere** [comment]
- what have I done this week? Added Jib dependency. Created and tested the docker image. Added PostGres on Heroku. #63 #62
 - what will I do next week? Work on presentation, small changes before Milestone3
 - what is holding me back? N/A

**Comment by kellyharrison** [comment]
-what have I done this week? 
Worked on presentation
-what will I do next week? 
complete presentation and #59
-what is holding me back?
N/A

**Comment by Dom123k** [comment]
- what have I done this week?(with link(s) to the relevant GitHub Issue(s))
   Worked on getting a nice design for the website #57 
- what will I do next week?(with link(s) to the relevant GitHub Issue(s))
  Finish #57 and project presentation
- what is holding me back? (if applicable)
 N/A

**Comment by cyang030** [comment]
- what have I done this week?
Presentation Topic and working on  #55
- what will I do next week?
Finish presentation and #55
- what is holding me back?
N/A

**Comment by AriSengupta** [comment]
- what have I done this week?(with link(s) to the relevant GitHub Issue(s))
Worked on #56
- what will I do next week?(with link(s) to the relevant GitHub Issue(s))
Finish working on #56
Finish presentation
- what is holding me back? (if applicable)
N/A

**Comment by MikeEvans6** [comment]
- what have I done this week?(with link(s) to the relevant GitHub Issue(s))
Worked on #61 and presentation
- what will I do next week?(with link(s) to the relevant GitHub Issue(s))
finish #61 and presentation
- what is holding me back? (if applicable)
