### ISSUE TITLE
Weekly Scrum [April 8th, 2021]

### ISSUE THREAD

**Issue by Dom123k** [thomas7carriere/Project4806#78]
- what have I done this week?(with link(s) to the relevant GitHub Issue(s))
- what will I do next week?(with link(s) to the relevant GitHub Issue(s))
- what is holding me back? (if applicable)

**Comment by cyang030** [comment]
- what have I done this week?(with link(s) to the relevant GitHub Issue(s))
#55 ,#72, presentation
- what will I do next week?(with link(s) to the relevant GitHub Issue(s))
NA
- what is holding me back? (if applicable)
NA

**Comment by kellyharrison** [comment]
- What have I done this week? Completed presenation and #59 
- What will I do next week? N/A
- What is holding me back? N/A

**Comment by Dom123k** [comment]
- what have I done this week?(with link(s) to the relevant GitHub Issue(s))
   Finished adding CSS to the html pages and added navigation bar. #57  
   Finished presentation 
- what will I do next week?(with link(s) to the relevant GitHub Issue(s))
   SYSC 4005 Project and 4th year project
- what is holding me back? (if applicable)
   N/A

**Comment by AriSengupta** [comment]
- what have I done this week?(with link(s) to the relevant GitHub Issue(s))
Finished working on #56
Finished presentation
- what will I do next week?(with link(s) to the relevant GitHub Issue(s))
N/A
- what is holding me back? (if applicable)
N/A

**Comment by MikeEvans6** [comment]
- what have I done this week?(with link(s) to the relevant GitHub Issue(s))
Patched edit survey feature #74 #75 
Worked on presentation
added back button feature #61 #69 
added a more comprehensive test #79  
- what will I do next week?(with link(s) to the relevant GitHub Issue(s))
N/A
- what is holding me back? (if applicable)
N/A

**Comment by thomas7carriere** [comment]
- What have I done this week? Finished work on presentation topic. Small changes and fixes.
 - What will I do next week? N/A
 - What is holding me back? N/A
