### ISSUE TITLE
Weekly Scrum- March 5th 2021

### ISSUE THREAD

**Issue by kellyharrison** [thomas7carriere/Project4806#9]
- what have I done this week?(with link(s) to the relevant GitHub Issue(s))  
- what will I do next week?(with link(s) to the relevant GitHub Issue(s))  
- what is holding me back? (if applicable)

**Comment by thomas7carriere** [comment]
- what have I done this week? Established a bare bones project on Github, building with TravisCI and deploying on Heroku. Worked on  #10 and #3.

 - what will I do next week? Continue to work on #10, ideally finishing early next week.
 - what is holding me back? Having trouble finding the best way to send the Survey data to the back end. Will discuss further with the team.

**Comment by cyang030** [comment]
- what have I done this week?(with link(s) to the relevant GitHub Issue(s))
  Implemented #2 OpeneEndedQuestion class
- what will I do next week?(with link(s) to the relevant GitHub Issue(s))
 #11 View survey page
- what is holding me back? (if applicable)
  NA

**Comment by MikeEvans6** [comment]
- what have I done this week?(with link(s) to the relevant GitHub Issue(s)) 
#12 Working on survey class.
- what will I do next week?(with link(s) to the relevant GitHub Issue(s)) 
Finish Survey Class.
- what is holding me back? (if applicable)
Other course assignment.

**Comment by Dom123k** [comment]
- what have I done this week?(with link(s) to the relevant GitHub Issue(s))
   Finished  implementing multiple choice class issue [#5](https://github.com/thomas7carriere/Project4806/projects/1#card-56210920)
   Merged multiple choice class #6 
- what will I do next week?(with link(s) to the relevant GitHub Issue(s))
   Additional testing. Maybe make dummy questions to put in database on start up
- what is holding me back? (if applicable)
  NA

**Comment by kellyharrison** [comment]
- what have I done this week?(with link(s) to the relevant GitHub Issue(s)):
This week I have created a UML diagram for the model of the projecT. I have also wrote the RangeQuestion() class issue #7 plus test casses to go with that class.

- what will I do next week?(with link(s) to the relevant GitHub Issue(s)):
Next week I will continue to add persistance tesing to the RangeQuestionTest() class issue #7 and I will also create a schema diagram for the project

- what is holding me back? (if applicable):
N/A

**Comment by AriSengupta** [comment]
- what have I done this week?(with link(s) to the relevant GitHub Issue(s))
  Working on ReadMe #21 
  Brainstorm work items for future sprints #15

- what will I do next week?(with link(s) to the relevant GitHub Issue(s))
  Finish updating ReadMe for Milestone 1 #21
  Create Tests for DTO Classes #20 
  Add Spring Boot Actuator Support for better debugging #24
  Enable H2 Console #25

- what is holding me back? (if applicable)
N/A
